### PR TITLE
remove obsolete ADDON_* methods (fixes build after xbmc/xbmc#12011)

### PR DESCRIPTION
**Pull request by herrnst**
Build-tested only, since I struggle to get something usable out of the VFS addon (even with https://github.com/xbmc/xbmc/pull/12004 applied my SACD ISOs won't show in music/files).

### CODE REVIEW

**Comment by notspiff** [comment]
.iso is not it the default music extensions.

**Comment by akva2** [comment]
(i'm notspiff but cba to change device); you painted yourself into my test-monkey corner trap: does it work for you after adding the extension ?

**Comment by herrnst** [comment]
Well, tried putting .iso into as.xml/musicextensions/add and even compiled it into xbmc/settings/as.cpp's m_musicExtensions, to no avail (kodi master from sometime yesterday) - no ISOs visible in music/files. Feel free to throw test code and/or instructions at me.

**Comment by notspiff** [comment]
That is all i do to make my whopping sample collection consisting of a single iso work :) will check with master tmrw but fairly certain i will come back positive. Need to dig up more isos. You are sure yours is scarlet book? If the addon is in flight it spews failures to terminal

**Comment by notspiff** [comment]
And just to be sure: you do know that the silly whitelist shit added to kodi means you have to manually enable addons in the browser

**Comment by herrnst** [comment]
Oh - got it working _once_ now, with the difference that I didn't try via the smb:// source, but through the local file system with the share mounted somewhere (once means kodi now yells things like "can't load shared library" randomly at me for whatever reason). Short: Works via the local file system, doesn't work using a network share.

**Comment by notspiff** [comment]
Communicatio  is such fun - could have told you so-  not expected to work as it still uses stdio for file access :)

**Comment by herrnst** [comment]
Now this is interesting: Kodi complains about that shared lib things when browsing to the ISOs is the first thing I do after starting Kodi. When I first try via smb:// and then browse through fsroot, it works and plays, but then fails to load/start the viz (shadertoy in this case). One ISO even makes Kodi crash. No such issues with all other "regular" formats though.

Crash BT without debug symbols: https://pastebin.com/au9aZBff

**Comment by herrnst** [comment]
Well, that's even 6 out of 11 ISOs I have here that make Kodi crash, didn't gdb/bt every single one though now.

**Pull request merged**
