### PR TITLE
Change to new C++ based addon interface style

### PR DESCRIPTION
**Pull request by lrusak**
This builds and loads ok but I have no sacd .iso file to test with. Can you give it a test?

### CODE REVIEW

**Comment by notspiff** [comment]
Asap but it will be next week probably

**Comment by lrusak** [comment]
crashes :disappointed: 
```
#0  0x00007fffd8966a31 in ADDON::CHelper_libXBMC_addon::OpenFile (this=0x0, strFileName=0x5bb2400 "/home/lukas/Come An' Get It.iso", 
    flags=0) at /usr/local/include/kodi/libXBMC_addon.h:323
#1  0x00007fffd8962f35 in sacd_vfs_input_open (target=0x5bb2400 "/home/lukas/Come An' Get It.iso")
    at /home/lukas/Documents/git/vfs.sacd/src/SACDFile.cpp:80
#2  0x00007fffd8968eb3 in sacd_open_image_file (location=0x5bb2400 "/home/lukas/Come An' Get It.iso")
    at /home/lukas/Documents/git/vfs.sacd/lib/libsacd/sacd_reader.c:66
#3  0x00007fffd89690ac in sacd_open (ppath=0x5baef80 "/home/lukas/Come An' Get It.iso")
    at /home/lukas/Documents/git/vfs.sacd/lib/libsacd/sacd_reader.c:200
```

**Comment by notspiff** [comment]
helper is null. isn't that thing all gone in new bindings ?

**Comment by notspiff** [comment]
pull 'develop' from origin, completely untested but that's some stuff i spotted that surely will break stuff.

**Comment by lrusak** [comment]
@notspiff your my hero! that's exactly what I needed and it works with your changes (I was able to score an sacd iso from a friend)

**Comment by notspiff** [comment]
great! i guess this is the contradiction to accompany 'never code in the blind' ;)

**Comment by notspiff** [comment]
now, depending on how interested you are in this thing: it has a big flaw; back when i dev'd this, ffmpeg could not handle DST (Digital Stream Transfer), the compression used in SACD isos. i thus have to decode this in the input layer, and that causes all sorts of issues with seeking, runtimes and such (not to mention, it's a cpu hungry beast due to a shoddy implementation). lately, there is a dst.c in ffmpeg, so somehow it should be possible to have ffmpeg accept the dst'd data directly. want to play and figure out how to do that?

**Comment by lrusak** [comment]
Sounds interesting maybe it's something that I can look into. For now I want to get some of the other vfs stuff cleaned up :+1:

**Comment by notspiff** [comment]
Squash and i will merge

**Comment by lrusak** [comment]
squashed

**Pull request merged**
